### ISSUE TITLE
First click of each session takes the previous session's date

### ISSUE THREAD

**Issue by nishathussain** [CRIPAC-DIG/SR-GNN#1]
https://github.com/CRIPAC-DIG/SR-GNN/blob/201f5d8f6c20fb2ada88060721d813eb26fa300e/datasets/preprocess.py#L41

`sessid = data['session_id']`
`if curdate and not curid == sessid:` could be replaced by 

`sessid = data['session_id']`
`curdate = ''`
`curdate = data['eventdate']`
`if curid>0 and not curid == sessid:`

**Comment by nishathussain** [comment]
there is no problem

**Comment by DebonairLi** [comment]
Hi, I have a problem.In yoochoose-clicks.dat, there are no titles like "session_id", "item_id"..., so I can't run preprocess.py successfully.So how to solve it?

**Comment by zhengzetao** [comment]
@DebonairLi
Using Editing software such as UltraEdit open the yoochoose-click.data directly and add the titles on it
