### ISSUE TITLE
about "performance of SRGNN with other baseline methods"

### ISSUE THREAD

**Issue by DebonairLi** [CRIPAC-DIG/SR-GNN#13]
Hi,

In your paper, the experiment result of Diginetica is 
![123](https://user-images.githubusercontent.com/36430942/55132115-44863d00-515c-11e9-8d5b-8616d5f15afc.png)
but in Stamp paper, their result is
![456](https://user-images.githubusercontent.com/36430942/55132129-536cef80-515c-11e9-8559-fa13519ba652.png)
We can see the values in Diginetica are different.So please tell me why.Thanks.

**Comment by yufengwhy** [comment]
RepeatNet，https://arxiv.org/pdf/1812.02646.pdf
> The scores reported in (Li et al. 2017b) on the DIGINETICA dataset differ because they did not sort the session items according to the “timeframe” field, which ignores the sequential information.
