### ISSUE TITLE
Reimplementation with a much more efficient package, PyTorch-Geometric

### ISSUE THREAD

**Issue by RuihongQiu** [CRIPAC-DIG/SR-GNN#17]
I have used [PyTorch_Geometric](https://github.com/rusty1s/pytorch_geometric) package to reimplement SR-GNN in this [repo](https://github.com/RuihongQiu/SR-GNN_PyTorch-Geometric) and achieve some similar results to your origin paper.

Would you mind if you can help add a link to my reimplementation?

@tangrizzly

**Comment by jimanvlad** [comment]
I te implemented in Tensorflow 2: https://github.com/jimanvlad/SR-GNN

**Comment by RuihongQiu** [comment]
Seems like there is no graph network package integrated with TensorFlow? I think that maybe graph computation specific package will accelerate the speed.

I have trouble in tunning the algorithm to make it converge for a few days. :)
Would you like to take a look at my code? It is short and clean. XDDD.

**Comment by SXKDZ** [comment]
added & thx!
