### ISSUE TITLE
如何对数据集中的session进行排序？

### ISSUE THREAD

**Issue by SamHaoYuan** [CRIPAC-DIG/SR-GNN#19]
作者您好:
感谢您的工作，我对数据集的预处理有一些疑问：
在Yoochoose数据集中，模型需要截取最近1/64和1/47以方便实验。在对session排序的时候，是依据一个session中最后一次点击的时间还是最开始点击的时间进行排序？我从代码中理解，是否只是取了读入数据的最后一个时间，而没有对session内部先进行排序？
谢谢！
If it is not convenient to use Chinese, I can restate my question in English. Thank you very much

**Comment by Aliang-CN** [comment]
> 作者您好:
> 感谢您的工作，我对数据集的预处理有一些疑问：
> 在Yoochoose数据集中，模型需要截取最近1/64和1/47以方便实验。在对session排序的时候，是依据一个session中最后一次点击的时间还是最开始点击的时间进行排序？我从代码中理解，是否只是取了读入数据的最后一个时间，而没有对session内部先进行排序？
> 谢谢！
> If it is not convenient to use Chinese, I can restate my question in English. Thank you very much

preprocess.py 代码里面第72行 sorted_clicks = sorted(sess_clicks[i], key=operator.itemgetter(1)) 这行代码就是对一个session内部进行排序
