### ISSUE TITLE
preprocessed file data format

### ISSUE THREAD

**Issue by nishathussain** [CRIPAC-DIG/SR-GNN#2]
Could you please explain the format of data written to the files.
`train.txt`, `test.txt` and `all_train_seq.txt`.
And what are `yoochoose1_4` and `yoochoose1_64` files (importance of 4 and 64)?

**Comment by tangrizzly** [comment]
The data is written to those files by `pickle.dump()`. After you use pickle to load the data, you can see the structure is `([session_list], target_list)`.
`yoochoose1_4` and `yoochoose1_64` main the most recent fractions 1/4 and 1/64 of the training sequences of Yoochoose respectively.
