### ISSUE TITLE
Inconsistent data descriptions

### ISSUE THREAD

**Issue by familyld** [CRIPAC-DIG/SR-GNN#20]
In the paper, it's reported that yoochoose 1/64 and 1/4 have 16,766 and 29,618 items respectively. However, using preprocess.py to process data results in 17,377 and 30,444 items respectively. Where are the missing items?

**Comment by SXKDZ** [comment]
The statistics reported in the paper is wrong. At the time we published the paper, we directly copied statistics from previous work. Sorry for that.
