### ISSUE TITLE
The code is inconsistent with the one described in paper

### ISSUE THREAD

**Issue by Yelrose** [CRIPAC-DIG/SR-GNN#21]
In your paper, it's mentioned that the graph is constructed by all the session.

In https://arxiv.org/pdf/1811.00855.pdf, page 6 the first paragraph under subtitle **Comparison with Variants of Connection Schemes**
`Firstly, we aggregate all session sequences together and
model them as a directed whole item graph, which is termed
as the global graph hereafter. `

But in your code, both your tensorflow and pytorch version, your code comment the build_graph function and model each session sequence as one small directed graph.

**Comment by SXKDZ** [comment]
The SR-GNN models each session sequence as a directed graph. The other are model variants.
