### ISSUE TITLE
When run yoochoose1_4, some problems happens

### ISSUE THREAD

**Issue by DebonairLi** [CRIPAC-DIG/SR-GNN#23]
![image](https://user-images.githubusercontent.com/36430942/59400670-d18b7a80-8dca-11e9-9170-6710a647c39f.png)
 Does anyone have such problem? And how to solve it?

**Comment by GalaxyCruiser** [comment]
Check the sublists of mask and see if every sublist is the same size.
Please print the data of mask.

**Comment by ZorrowHu** [comment]
Hi, I'm wondering how I could run code on dataset yoochoose? I tried TITAN XP with 12GB RAM but encountered OUT OF MEMORY problems, so I want to know how you can do it?(Maybe you use DataParallel? I tried that buf failed. If so pls tell me how to) Thx in advance!
