### ISSUE TITLE
用的测试数据 loss 一直在48点多,这是预期效果吗？

### ISSUE THREAD

**Issue by Alucardmini** [CRIPAC-DIG/SR-GNN#24]
![image](https://user-images.githubusercontent.com/8130720/59426793-ab39ff00-8e0b-11e9-838d-a65e1283cbb0.png)

**Comment by lfywork** [comment]
You may be use the small sample dataset. The  result you show indicates that the model over fit? or achieves the its' upper bound.

I suggest you are able to try more big dataset.

**Comment by WJSAI** [comment]
截图里的结果不是只有28吗，为啥说48点多？
