### ISSUE TITLE
ggnn函数代码疑问

### ISSUE THREAD

**Issue by searchlink** [CRIPAC-DIG/SR-GNN#25]
感谢提供基于session的图网络的推荐想法！我在复现代码的过程中，对于`tensorflow_code`文件下的`model.py`中ggn定义有点疑问，如果`self.step>1`，当i=0时，经过`tf.nn.dynamic_rnn`输出的`fin_state`的`shape:(batch_size, out_size)`, 而当i = 1时，` self.adj_in`的`shape: (batch_size, max_uniq_len, max_uniq_len)`.对于`tf.matmul(self.adj_in, fin_state_in)`， 按照shape来看，`(batch_size, max_uniq_len, max_uniq_len) * (batch_size, 1, out_size)`根本无法矩阵运算，麻烦解答~多谢！

**Comment by Aliang-CN** [comment]
> 感谢提供基于session的图网络的推荐想法！我在复现代码的过程中，对于`tensorflow_code`文件下的`model.py`中ggn定义有点疑问，如果`self.step>1`，当i=0时，经过`tf.nn.dynamic_rnn`输出的`fin_state`的`shape:(batch_size, out_size)`, 而当i = 1时，` self.adj_in`的`shape: (batch_size, max_uniq_len, max_uniq_len)`.对于`tf.matmul(self.adj_in, fin_state_in)`， 按照shape来看，`(batch_size, max_uniq_len, max_uniq_len) * (batch_size, 1, out_size)`根本无法矩阵运算，麻烦解答~多谢！

我也遇到了这个问题了

**Comment by searchlink** [comment]
@linxingliang  你可以去参考paddle的代码，比较清楚
