### ISSUE TITLE
当其中一个session为[238, 238, 238, 0, 0]时，怎么构造邻接矩阵的问题

### ISSUE THREAD

**Issue by lfywork** [CRIPAC-DIG/SR-GNN#27]
https://github.com/CRIPAC-DIG/SR-GNN/blob/90123c88850eec8c574518fee6e46aefb42acb94/pytorch_code/utils.py#L95

你好，我想问问为什么这一行的代码不是 u_A[u][v] += 1 ？

**Comment by SXKDZ** [comment]
我们没有考虑重复的session clicks。
