### ISSUE TITLE
去掉GGNN后测试集效果更好

### ISSUE THREAD

**Issue by WJSAI** [CRIPAC-DIG/SR-GNN#28]
作者您好，非常感谢您的开源，有个问题想请教一下：

对于tensorflow 的代码，我在diginetica数据集上做了两个实验：
1. 正常运行，在第三个3epoch 达到最好，Recall@20: 50.0131 | MMR@20: 16.3228
2. 去掉GGNN部分，在第三个3epoch 达到最好，Recall@20: 50.4795 | MMR@20: 16.9137
从实验结果上看，加入GGNN后反而会降低实验效果，请问我是哪里出了问题吗？

**Comment by SXKDZ** [comment]
Hello,

Thanks for your interest on our paper. GGNN is just one way to get node embeddings. Therefore, feel free to change GNN models :) Since we only set t = 1, it is possible that vanilla GNN outperforms GGNN, due to less parameters.

**Comment by ZorrowHu** [comment]
Hi! 你在代码运行的时候遇到OUT OF MEMORY爆显存的问题了吗？你是怎么解决的呢？
