### ISSUE TITLE
Memory Error when running yoochoose1_4, how much RAM is needed to run it?

### ISSUE THREAD

**Issue by GalaxyCruiser** [CRIPAC-DIG/SR-GNN#29]
When i run the yoochoose1_4 experiment, it run out of 32GB RAM, how much RAM is needed to run it?

**Comment by SXKDZ** [comment]
We use a server with 8 Titan Xp graphics cards.

**Comment by ZorrowHu** [comment]
> We use a server with 8 Titan Xp graphics cards.

Hi! Can you share the code how to use graphic card in parallel? I tried torch.nn.DataParallel but it didn't work, only utilizing one graph card.
