### ISSUE TITLE
数据处理问题

### ISSUE THREAD

**Issue by WJSAI** [CRIPAC-DIG/SR-GNN#31]
作者您好，非常感谢您的开源，请教两个问题：
1. 请问为什么在diginetica数据集下，论文中报的STAMP的实验结果（P@20 45.64）与STAMP自己的结果（P@20 62.03）降低那么多呢？
2. Yoochoose 1/4 数据集的clicks用您的代码处理后是7911603并不是论文中报的8,326,407，请问我是哪里出问题了吗？

**Comment by SXKDZ** [comment]
感谢您对我们文章的兴趣

1. 与NARM作者进行了沟通，我们发现diginetica数据集中timeframe理解不太明确。我们论文最终版对这个field进行了排序，保证session内有序。STAMP的作者联系不上。

2. 论文中应该是写错了。
