### ISSUE TITLE
数据集统计问题

### ISSUE THREAD

**Issue by HelloMrG** [CRIPAC-DIG/SR-GNN#32]
你好，想请教一下，你们的论文中数据集统计的那张表of clicks是怎么统计的呢，我这边按照你们的数据处理方法，统计列表中除了of clicks外基本都对的上，只有of clicks，差距较大，特别是Yoochoose 1/4的of clicks，训练集+测试及合在一起的clicks也只有7911599条

**Comment by SXKDZ** [comment]
Duplicate of #20
