### ISSUE TITLE
Tensorflow and PyTorch code have different performance

### ISSUE THREAD

**Issue by weitianxin** [CRIPAC-DIG/SR-GNN#33]
I tried to do experiments on the Diginetica dataset with the Tensorflow code, but I don't know why the P@20 can only reach 49.8. However, P@20 in PyTorch code can achieve the same performance as the paper, 50.7, and the hyperparameters and model look the same as Tensorflow. I am confused and hope to find a solution. Thank you very much.

**Comment by SXKDZ** [comment]
The Tensorflow version is for your reference only.

**Comment by mmaher22** [comment]
What do you mean by for your reference? 

I have tried also both implementations in multiple experiments and they have very different performance

**Comment by SXKDZ** [comment]
The reported performance is based on PyTorch version released in this repo. You may kindly refer to other implementations listed here but their performance is not guaranteed.

**Comment by Coder-Yu** [comment]
SR-GNN can not beat other baselines such as NARM on Diginetica. Referring to the paper of NARM, you will see the result of NARM was lowered in this paper, while SR-GNN and NARM use the same preprocessing method. The results in this paper cannot reflect the truth. In other words, there is human intervention when reporting the results.
