### ISSUE TITLE
Inconsistent performance of POP

### ISSUE THREAD

**Issue by chenjh1988** [CRIPAC-DIG/SR-GNN#36]
In the paper, it reported that the performance of POP in yoochoose1_64 is 6.71 (P@20). However, when I reimplement POP, I got different result 7.36. Could you open the source code and the parameter setting of baselines?

**Comment by SXKDZ** [comment]
The baseline performance is based on NARM and STAMP's for consistency. However, I in person don't believe such small a difference matters much.
