### ISSUE TITLE
Are you make it along with the original paper?

### ISSUE THREAD

**Issue by CodeCollection2018** [CRIPAC-DIG/SR-GNN#4]
I have visited the original paper.But I find confusion in this code where GNN Class is implemented.Are you make it along with the original paper?In original paper,it users Gated Graph Neural Network.Do you do it in a common GNN style?

**Comment by SXKDZ** [comment]
Thank you for pointing out. There's a weight parameter missing in the paper published on arXiv. In our implementation, there should be a weight matrix following the adjacency matrix multiplied with the list of item vectors (Equation 1). We have corrected this problem in the final version and will update the paper when the final conference proceeding is available.

**Comment by TimHsu1998** [comment]
I have two questions for the paper.  
1. In equation (6), is _m_ the number of items in a session or in the whole dataset? 
2. Is the _Vi_ in equation (6) the same as the _Vi_ in equation (8)? The one in (6) seems to be put into (1) ~ (5), but the one in (8) is not.

**Comment by SXKDZ** [comment]
> I have two questions for the paper.
> 
> 1. In equation (6), is _m_ the number of items in a session or in the whole dataset?
> 2. Is the _Vi_ in equation (6) the same as the _Vi_ in equation (8)? The one in (6) seems to be put into (1) ~ (5), but the one in (8) is not.

Thank you for your interest in our paper.

A1: m refers to the number of all unique items.
A2: Vector $\mathbf{v}_i$ in bold denotes the embedding of item $v_i$.

**Comment by TimHsu1998** [comment]
> > I have two questions for the paper.
> > 
> > 1. In equation (6), is _m_ the number of items in a session or in the whole dataset?
> > 2. Is the _Vi_ in equation (6) the same as the _Vi_ in equation (8)? The one in (6) seems to be put into (1) ~ (5), but the one in (8) is not.
> 
> Thank you for your interest in our paper.
> 
> A1: m refers to the number of all unique items.
> A2: Vector $\mathbf{v}_i$ in bold denotes the embedding of item $v_i$.

Thank you for your reply, but I still feel confused about this. 

If the m in equation (6) is the number of all unique items in the whole dataset, the size of alpha in line 84 of pytorch_code/model.py should be batch_size * number_all_unique_items * 1, but it is batch_size * seq_length * 1 when I run the code.

**Comment by SXKDZ** [comment]
> > > I have two questions for the paper.
> > > 
> > > 1. In equation (6), is _m_ the number of items in a session or in the whole dataset?
> > > 2. Is the _Vi_ in equation (6) the same as the _Vi_ in equation (8)? The one in (6) seems to be put into (1) ~ (5), but the one in (8) is not.
> > 
> > 
> > Thank you for your interest in our paper.
> > A1: m refers to the number of all unique items.
> > A2: Vector $\mathbf{v}_i$ in bold denotes the embedding of item $v_i$.
> 
> Thank you for your reply, but I still feel confused about this.
> 
> If the m in equation (6) is the number of all unique items in the whole dataset, the size of alpha in line 84 of pytorch_code/model.py should be batch_size * number_all_unique_items * 1, but it is batch_size * seq_length * 1 when I run the code.

Our mistake. Thanks for pointing our. It should be summing over all items within one session, so the m in Eq. (6) should be changed to n.
