### ISSUE TITLE
about the connection matrix

### ISSUE THREAD

**Issue by ucasiggcas** [CRIPAC-DIG/SR-GNN#42]
hi,dear
paper中的连接矩阵是指左边的吗？还是说全部啊，右边的部分没看懂啊？咋理解啊？
多谢
![image](https://user-images.githubusercontent.com/35590066/86572620-c1ca6f80-bfa5-11ea-93b0-7ebef391e86f.png)

**Comment by SXKDZ** [comment]
可以对照代码看论文中公式（1）的实现。
