### ISSUE TITLE
论文示意图与代码不符？

### ISSUE THREAD

**Issue by Coder-Yu** [CRIPAC-DIG/SR-GNN#49]
看论文的model overview，用于训练和预测的应该是经过了GNN之后得到的item embedding，但是代码里是用的第0层的item embedding？作者求解释一下？

**Comment by SpaceLearner** [comment]
代码里面就是经过了GNN的，只是匹配的时候目标item的embedding用的第0层

**Comment by Coder-Yu** [comment]
> 代码里面就是经过了GNN的，只是匹配的时候目标item的embedding用的第0层

建议你再看下Figure 1，上面显示做softmax的时候用的是经过图卷积的item embedding还是第0层的。
既然代码用的第0层，overview就不要误导人。希望作者给解释一下。

**Comment by SpaceLearner** [comment]
我又看了一下，这他确实不符合。并且还有一点，他这个模型去掉GNN后表现并没有降低，感觉这个GNN的部分基本上没啥用。

**Comment by Coder-Yu** [comment]
> 我又看了一下，这他确实不符合。并且还有一点，他这个模型去掉GNN后表现并没有降低，感觉这个GNN的部分基本上没啥用。

为了蹭热点而没有做ablation study的文章，出这种情况很正常。还是希望作者给解释一下图码不符的原因

**Comment by SpaceLearner** [comment]
关键之后的顶会上（Sigir之类）出了一堆follow这篇工作用Session Graph的，真难知道到底work不work

**Comment by SXKDZ** [comment]
代码里`pytorch_code/model.py`第91行，`hidden`经过`embedding_lookup`以后再经过了GNN。

另，也有其他组在其他数据集上进行了实验：
如：
> M. Ludewig, N. Mauro, S. Latifi, and D. Jannach, “Empirical Analysis of Session-Based Recommendation Algorithms,” User Model. User-Adapt. Interact., pp. 1–33, Oct. 2020.

我们的方法在neural方法中效果都不错。
希望理性平和交流，阴阳怪气的回复下次会删除。

**Comment by Coder-Yu** [comment]
> 代码里`pytorch_code/model.py`第91行，`hidden`经过`embedding_lookup`以后再经过了GNN。
> 
> 另，也有其他组在其他数据集上进行了实验：
> 如：
> 
> > M. Ludewig, N. Mauro, S. Latifi, and D. Jannach, “Empirical Analysis of Session-Based Recommendation Algorithms,” User Model. User-Adapt. Interact., pp. 1–33, Oct. 2020.
> 
> 我们的方法在neural方法中效果都不错。
> 希望理性平和交流，阴阳怪气的回复下次会删除。

说的是你们做prediction的时候用的第0层embedding。自己看下tensorflow和pytorch版本里面哪个在最终预测的时候用了卷积后的item embedding了？构造session embedding的时候确实用到了卷积的item embedding，也没人说这里有问题吧。明明代码文章不符，读者质疑就是阴阳怪气。卷积这块本来也没来带什么提升，怎么还不让说了呢。
