### ISSUE TITLE
Statistics of items in Yoochoose(both) data not matching.

### ISSUE THREAD

**Issue by gourxb** [CRIPAC-DIG/SR-GNN#5]
We processed data as you mentioned and the number of train and test sessions are matched.   

    with open('../yoochoose1_64/train.txt','rb')as f:
        train=cPickle.load(f)
    print("len of train",len(train[0]))
    with open('../yoochoose1_64/test.txt','rb')as f:
        test=cPickle.load(f)
    print("len of test",len(test[0]))

    len of train 369859
    len of test 55898

But, you reported that count of all items in yoochoose1/64 data as 16766. We are getting a different number. Same problem with Yoocooose1/4 data also. Please find our code.
    `#train sequences and labels`
    `train_seq=train[0]`
    `train_y=train[1]`
    `#test sequences and labels`
    `test_seq=test[0]`
    `test_y=test[1]`
    `# find unique items in the train sequences`
    `full_train = [j for sub in train_seq for j in sub]`
    `print("count of items ",len(set(full_train)))`

    `count of items16373`

Can you please mention the code to find count of items?

**Comment by ghost** [comment]
The 'avg.length' seems also inconsistent with what reported in paper, for example, the average length of sessions in Diginetica dataset is about 4.85 using the method in your code, but 5.12 in paper. I don't know if it's just to be consistent with NARM, which I think is unnecessary.

**Comment by tangrizzly** [comment]
Yes. Both are just to be consistent with NARM.
