### ISSUE TITLE
Problem of preprocess.py

### ISSUE THREAD

**Issue by DebonairLi** [CRIPAC-DIG/SR-GNN#9]
![1552403425(1)](https://user-images.githubusercontent.com/36430942/54211609-943df500-451c-11e9-8cd6-59d07ef9c43b.jpg)
For diginetica, I run it sucessfully, but for yoochoose, I can't.In yoochoose-clicks.dat, there are no titles like "item_id", "Session_id", so I want to know how to revise it.Thank you.

**Comment by cowry5** [comment]
Have you solved the problem? I have also encountered this problem

**Comment by DebonairLi** [comment]
> Have you solved the problem? I have also encountered this problem
哈哈哈，最简答的方法就是打开那个文件把那几个表头加上去。。。文件可能比较大，打开以及修改需要时间。就酱紫

**Comment by cowry5** [comment]
THX :)
谢谢，哈哈

**Comment by Weiwei-Tian** [comment]
> > Have you solved the problem? I have also encountered this problem
> > 哈哈哈，最简答的方法就是打开那个文件把那几个表头加上去。。。文件可能比较大，打开以及修改需要时间。就酱紫

请问用什么软件打开修改呀？

**Comment by YinghongZhang** [comment]
You can add fieldnames at codeline 31, csv.DictReader parameters, like this:
reader = csv.DictReader(f, fieldnames = ['session_id', 'timestamp', 'item_id', 'category'], delimiter=',')
also, you can use csv.DictWriter to write header to csv file, but it's more easy to just add headers when read file.
